name: Kilted

on:
  push:
    branches:
      - main
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:kilted

    steps:
      - uses: actions/checkout@v4
        with:
          path: ros_ws/src/RVizSplat

      - name: Checkout splat_interfaces
        uses: actions/checkout@v4
        with:
          repository: splat-ros/splat_interfaces
          path: ros_ws/src/splat_interfaces

      - name: Install system dependencies
        run: |
          apt-get update
          rosdep update
          rosdep install \
            --from-paths ros_ws/src \
            --ignore-src \
            --rosdistro kilted \
            --skip-keys ament_python \
            -y
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build
        run: |
          . /opt/ros/kilted/setup.sh
          cd ros_ws
          colcon build --symlink-install --event-handlers console_cohesion+
